### ISSUE TITLE
The babel config is outdated and `react-native run-ios` is not working anymore.

### ISSUE THREAD

**Issue by flyingant** [netease-im/NIM_ReactNative_Demo#15]
The original .babelrc leads to some errors because of upgrading?

Updated the .babelrc file to the below and added necessary modules to get to work:
```
{
  "presets": [
    "module:metro-react-native-babel-preset"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
}

```

**Comment by Warmriver** [comment]
I also have this issue. react-native run-ios command does not work with the original .babelrc config. But flyingant's solution didn't get to work neither.

**Comment by lostomato** [comment]
I have the same issue. Build successful but show error while running the app.

The decorators plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. 
If you want to use the legacy decorators semantics, you can set the 'legacy: true' option.

**Comment by Claiyre** [comment]
Thanks for issue.
The babel now works fine. 
And "run-ios" doesn't work is a bug of react-native, please refer to [https://github.com/facebook/react-native/issues/23282#issuecomment-476439080](this)
