### ISSUE TITLE
这个Demo里是没有音视频即时通话的

### ISSUE THREAD

**Issue by lostomato** [netease-im/NIM_ReactNative_Demo#19]
打电话问了客服，
客服说技术部没有做出来
是不是因为音视频通信在RN上体验太差吗
有人在RN实现过吗

**Comment by EvianZhow** [comment]
可以拿官方 Demo 中提取音视频通话部分的代码，安卓叫 avchatkit，然后自己集成。但一旦要升级，会比较麻烦。
