### ISSUE TITLE
Android 官方sdk已经跟新到6.8.0了，RN什么时候更新？

### ISSUE THREAD

**Issue by BestKai** [netease-im/NIM_ReactNative_Demo#22]

**Comment by Claiyre** [comment]
RN SDK 目前最新版本是 6.7.0 
可以在 [这里](https://dev.yunxin.163.com/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/Web%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/ReactNative) 查看下载

**Comment by BestKai** [comment]
下载下来的包有问题，直接替换包崩溃，js中初始化方法和java中的初始化方法不一致
<img width="765" alt="WeChat5e93f0c36aa838587aea73dcbd62fa8c" src="https://user-images.githubusercontent.com/8436462/64008172-26c46600-cb48-11e9-878d-9d37a49080da.png">
<img width="679" alt="WeChat0bf573f977ddc7b8cb7033537ebf0c61" src="https://user-images.githubusercontent.com/8436462/64008184-29bf5680-cb48-11e9-985e-adce827a92dc.png">

**Comment by Claiyre** [comment]
不好意思 是我们疏漏，之前的jar包有点问题，修改后的包今天中午一点已经更新了，请重新下载，替换nimpush文件夹即可（更新了nimpush/libs/rnlibs.jar）

**Comment by BestKai** [comment]
你们提供的jar包没问题了， 但是你们提供的NIMPushModule.java 是这样的@ReactMethod public void init( String xmAppId, String xmAppKey, String xmCertificateName, String hwCertificateName, String mzAppId, String mzAppKey, String mzCertificateName, String fcmCertificateName, final Callback tokenCallback)。缺少了部分参数

**Comment by gitfdy** [comment]
6.7的版本依然是14个参数,但是nimpush的里面还是9个参数,希望能及时更正一下,现在已经不得已使用回了6.1的版本
