### ISSUE TITLE
消息推送配置完后收不到推送消息

### ISSUE THREAD

**Issue by maxrisk** [netease-im/NIM_ReactNative_Demo#23]
有弹权限提示框，但是收不到推送是怎么回事，怎么排查

**Comment by maxrisk** [comment]
用 Pusher 推送工具测试是可以推送成功的，但 SDK 的不行

**Comment by ma6566966** [comment]
配置文件的iosPushConfig改成你的证书名称

**Comment by everlose** [comment]
This issue is closed because the time has passed for a long time. If you haven't solved this problem, welcome to open a new issue
