### ISSUE TITLE
ios端报错

### ISSUE THREAD

**Issue by LingCn** [netease-im/NIM_ReactNative_Demo#34]
PushKit apps that use VoIP push must link either CallKit or IncomingCallNotifications frameworks.

**Comment by everlose** [comment]
> PushKit apps that use VoIP push must link either CallKit or IncomingCallNotifications frameworks.

请确认下

* 你的 node 版本，
* 是自己在 xcode 上编译的吗？目标编译版本选择了多少？

我在 xcode 11.5 上编译 IOS 12 和 IOS 13，没有遇到你的那个问题。或者你可以尝试下 stackoverflow 上所说的

> Embedding CallKit.framework in General Settings of the Project resolves this issue.
> On iOS 13, Apple now mandates that all VoIP push notifications be reported to the CallKit framework as a new call
