### ISSUE TITLE
安卓无法启动

### ISSUE THREAD

**Issue by icyfe** [netease-im/NIM_ReactNative_Demo#40]
Error: Type com.xiaomi.push.service.af is referenced as an interface from `com.xiaomi.push.service.bd`.

![image](https://user-images.githubusercontent.com/44893721/93315448-a8636080-f83d-11ea-9bf2-d9a43987c98a.png)

**Comment by everlose** [comment]
关闭这个 issue 是因为时间已经过去了很久，若您还没能解决这个问题，欢迎在开新的 issue
