### ISSUE TITLE
onMsg问题

### ISSUE THREAD

**Issue by marlti7** [netease-im/NIM_ReactNative_Demo#43]
`onmsg(msg) {
        if (nimStore.currentSessionId === msg.sessionId) {
          // nimStore.currentSessionMsgs.push(msg);
          nimStore.currentSessionMsgs = nimStore.currentSessionMsgs.concat([msg]);
          // set(nimStore, 'currentSessionMsgs', nimStore.currentSessionMsgs.concat([msg]));
          constObj.nim.sendMsgReceipt({
            msg,
            done: function sendMsgReceiptDone(error) {
              // do something
              console.log(error);
            },
          });
        }`
        
        按你代码这样写的话  sdk只有在进入聊天房间才会存在nimStore.currentSessionId， 而当退出app重新进入app的时候，在聊天列表时 ，是没有nimStore.currentSessionId 这样的话 监听到 新消息时， 再进入聊天房间 是没有缓存新消息的

**Comment by everlose** [comment]
我明白你的意思，然而这只是个demo，您可以提 issue 来补充您这个改进。
