### ISSUE TITLE
ios项目无法启动 

### ISSUE THREAD

**Issue by tmzhenzheng** [netease-im/NIM_ReactNative_Demo#6]
The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm
	Analyze Modules/RCTUIManager.m
(2 commands with analyzer issues)

The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/NIM_ReactNative_Demo.app/NIM_ReactNative_Demo normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/NIM_ReactNative_Demo.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by Liqiankun** [comment]
没有个两三天时间，项目是运行不起来的！

**Comment by king3366ster** [comment]
rn初始化常见的会有boost glog等库不全导致编译报错
可以参考：
https://stackoverflow.com/questions/48540944/config-h-file-not-found-react-native-ios
https://blog.csdn.net/u011154205/article/details/79820860

**Comment by zhYAO** [comment]
> 没有个两三天时间，项目是运行不起来的！

你是怎么运行起来的  能说说吗

**Comment by Liqiankun** [comment]
@zhYAO 我放弃了，自己用iOS SDK做的
