### ISSUE TITLE
能不能把这个IM库抽成一个库，可以自己安装

### ISSUE THREAD

**Issue by 25juan** [netease-im/NIM_ReactNative_Demo#7]
能不能把这个demo 里面的sdk 抽成一个库进自定义安装改造，而不是与demo 里面的UI绑定起来

**Comment by qdsang** [comment]
UI太丑了，仿微信就完美了

**Comment by yoonzm** [comment]
@25juan SDK应该就只是nim/NIM_WEB_SDK_rn_v5.7.0.js这一个js文件吧

**Comment by king3366ster** [comment]
> @qdsang 这个demo跑起来，账号密码不对，那账号密码是什么？你知道吗

试一下 000, 001, 002 ... 密码都是123456

**Comment by king3366ster** [comment]
> @25juan SDK应该就只是nim/NIM_WEB_SDK_rn_v5.7.0.js这一个js文件吧

demo 上是的，用法跟普通浏览器上js sdk是一样的
